name: sample

on: 
  workflow_dispatch:
  repository_dispatch:
  
env:
  sample_name: sample_value

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: echo "${{sample_name}}"
