name: sample

on: 
  workflow_dispatch:
  repository_dispatch:
  
env:
  sample_name: sample_value
  repo: ${{ env.GITHUB_REPOSITORY }}

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      run: echo "$repo"
